@SwcsScanner.Api_HostAddress = https://localhost:5001

POST {{SwcsScanner.Api_HostAddress}}/api/v2/auth/login
Content-Type: application/json

{
  "username": "user01",
  "password": "1234"
}

###

GET {{SwcsScanner.Api_HostAddress}}/api/v2/products/lookup?barcode=6925303714857
Accept: application/json
Authorization: Bearer <replace_token>

###
